# Generated by Django 5.2.1 on 2025-06-03 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='person',
        ),
        migrations.RemoveField(
            model_name='education',
            name='institution',
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.education')),
            ],
        ),
        migrations.DeleteModel(
            name='Names',
        ),
    ]
